### ISSUE TITLE
The example in the readme is not compatible with Circuitpython

### ISSUE THREAD

**Issue by Neradoc** [adafruit/Adafruit_CircuitPython_datetime#12]
The example in the readme gets 2 errors in Circuitpython:
```py
print("Current UTC time: ", datetime.now(timezone.utc))
```
```
Traceback (most recent call last):
  File "code.py", line 13, in <module>
  File "adafruit_datetime.py", line 1356, in now
  File "adafruit_datetime.py", line 1328, in fromtimestamp
  File "adafruit_datetime.py", line 1306, in _fromtimestamp
NotImplementedError: CircuitPython does not currently implement time.gmtime.
```

```py
print(
    "The {1} is {0:%d}, the {2} is {0:%B}, the {3} is {0:%I:%M%p}.".format(
        dt, "day", "month", "time"
    )
)
```
```
Traceback (most recent call last):
  File "code.py", line 23, in <module>
ValueError: invalid format specifier
```
Should it be replaced with the simpletest example code ?

**Comment by ladyada** [comment]
yes plz!
